import datetime

from langchain.tools import tool
import memory.database as db

# Descriptions are generated by AI

# Event tools

@tool
def add_event_tool(title: str, start: str, end: str, location: str, description: str) -> str:
    """Save a new calendar event to the database.

    Use whenever the user schedules, books, or mentions an upcoming event —
    including lectures, meetings, appointments, exams, deadlines, or social
    activities. Do NOT call this to look up or modify an existing event.

    Args:
        title: Short human-readable name for the event.
            Examples: "Doctor appointment", "Math lecture", "Team standup"
        start: Start datetime in ISO 8601 format "YYYY-MM-DDTHH:MM:SS".
            If the user gives only a date use "T00:00:00" for the time.
            If only a time is given and the user says "today", use today's date.
            Examples: "2026-05-12T09:00:00", "2026-06-01T00:00:00"
        end: End datetime in ISO 8601 format, or "" if unknown.
            Examples: "2026-05-12T10:30:00", ""
        location: Where the event takes place, or "" if not mentioned.
            Examples: "Room 4B", "Zurich HB", ""
        description: Extra context, notes, or remarks, or "" if none.
            Examples: "Bring ID card", "Zoom link: meet.example.com", ""

    Returns:
        Confirmation string with the stored title and time range.
    """
    db.add_event(
        title=title,
        start_time=start,
        end_time=end,
        location=location,
        description=description,
    )
    return f"Event added: '{title}' from {start} to {end or 'open end'}."


@tool
def get_events_tool() -> str:
    """Return every calendar event in the database, regardless of date.

    Use when the user wants a full overview of all events, or when you need
    to browse events to find an ID before editing or deleting.
    Do NOT use just to check today — use get_today_events_tool instead.

    Returns:
        List of all event dicts with keys: id, title, start_time, end_time,
        location, description, status.
    """
    return return_or_empty(db.get_all_events())


@tool
def delete_event_by_id_tool(id: int) -> str:
    """Permanently delete a calendar event from the database by its ID.

    Use when the user wants to remove or cancel a specific event.
    ALWAYS call search_event_tool or list_all_events_tool first to get the
    correct ID — never guess or invent one.

    Args:
        id: Integer primary key of the event to delete.
            Must be obtained from a prior tool call, never assumed.
            Example: 7

    Returns:
        Confirmation string that the event was deleted.
    """
    db.delete_event_by_id(id)
    return f"Event {id} has been deleted."


# User profile tools

@tool
def update_user_name_tool(name: str) -> str:
    """Store or update the user's name in their profile.

    Use the first time the user mentions their name, or when they correct it.

    Args:
        name: The user's full name or preferred display name.
            Examples: "Anna", "Max Müller", "AJ"

    Returns:
        Confirmation string with the stored name.
    """
    db.update_user_name(name)
    return f"Name updated to '{name}'."


@tool
def update_user_birthdate_tool(birthdate: str) -> str:
    """Store or update the user's date of birth in their profile.

    Use when the user mentions or shares their birthday.

    Args:
        birthdate: Date of birth in ISO 8601 format "YYYY-MM-DD".
            Convert natural-language dates before calling.
            Examples: "1995-08-23", "2000-01-01"

    Returns:
        Confirmation string with the stored birthdate.
    """
    db.update_user_birthdate(birthdate)
    return f"Birthdate updated to {birthdate}."


@tool
def get_user_tool() -> str:
    """Retrieve the user's name and birthdate.

    Use when you need the users name or birthdate.

    Returns:
        List containing one user dict with keys: id, name, birthdate.
    """
    return return_or_empty(db.get_user())


# Grocery tools

@tool
def add_grocery_tool(text: str) -> str:
    """Add a single item to the user's grocery / shopping list.

    Use when the user wants to remember to buy something.
    Call once per distinct item — do NOT combine multiple items into one call.

    Args:
        text: The grocery item, optionally with quantity or brand.
            Examples: "milk", "2 kg potatoes", "organic oat milk"

    Returns:
        Confirmation that the item was added.
    """
    db.add_grocery(text)
    return f"'{text}' added to groceries."


@tool
def list_groceries_tool() -> str:
    """Return all active (not yet purchased) items on the grocery list.

    Use when the user asks what's on their shopping list, or when you need
    an item's ID before marking it done or deleting it.

    Returns:
        List of grocery dicts with keys: id, grocery, amount, notes, status.
        Empty list if the list is clear.
    """
    return return_or_empty(db.get_groceries())


@tool
def set_grocery_done_tool(id: int) -> str:
    """Mark a grocery item as purchased / done (soft-delete, record is kept).

    Use when the user says they've bought a specific item.
    ALWAYS call list_groceries_tool first to get the correct ID.

    Args:
        id: Integer ID of the grocery item to mark as done.
            Must come from a prior list_groceries_tool call — never guessed.
            Example: 3

    Returns:
        Confirmation that the item was marked done.
    """
    db.update_grocery(id)
    return f"Grocery item {id} marked as done."


@tool
def remove_grocery_tool(id: int) -> str:
    """Permanently delete a grocery item from the list.

    Use when the user explicitly wants to remove an item entirely (not just
    tick it off). ALWAYS call list_groceries_tool first to confirm the ID.

    Args:
        id: Integer ID of the grocery item to delete permanently.
            Must come from a prior list_groceries_tool call — never guessed.
            Example: 5

    Returns:
        Confirmation that the item was removed.
    """
    db.delete_grocery(id)
    return f"Grocery item {id} removed."


# Note tools

@tool
def add_note_tool(text: str) -> str:
    """Save a new note or reminder to the user's notes list.

    Use for anything the user wants to remember that is not a calendar event
    or grocery item — tasks, ideas, to-dos, short memos.

    Args:
        text: Full content of the note. Be specific so the note is
            self-contained when read back later.
            Examples: "Call insurance about the claim",
                      "Read chapter 4 before Thursday",
                      "Gym locker code: 1842"

    Returns:
        Confirmation that the note was saved.
    """
    db.add_note(text)
    return f"Note saved: '{text}'."


@tool
def list_notes_tool() -> str:
    """Return all active (not yet completed) notes.

    Use when the user asks to see their notes, tasks, or reminders, or when
    you need a note's ID before marking it done or deleting it.

    Returns:
        List of note dicts with keys: id, note, status.
        Empty list if there are no active notes.
    """
    return return_or_empty(db.get_notes())


@tool
def set_note_done_tool(id: int) -> str:
    """Mark a note or task as completed (soft-delete, record is kept).

    Use when the user says they've finished a task or reminder.
    ALWAYS call list_notes_tool first to find the correct ID.

    Args:
        id: Integer ID of the note to mark as done.
            Must come from a prior list_notes_tool call — never guessed.
            Example: 2

    Returns:
        Confirmation that the note was marked done.
    """
    db.update_notes(id)
    return f"Note {id} marked as done."


@tool
def remove_note_tool(id: int) -> str:
    """Permanently delete a note from the database.

    Use when the user explicitly wants a note gone entirely, not just ticked
    off. ALWAYS call list_notes_tool first to confirm the ID.

    Args:
        id: Integer ID of the note to delete permanently.
            Must come from a prior list_notes_tool call — never guessed.
            Example: 4

    Returns:
        Confirmation that the note was deleted.
    """
    db.delete_note(id)
    return f"Note {id} deleted."


@tool
def delete_done_tool() -> str:
    """Permanently remove ALL items marked as done from groceries and notes.

    Use when the user wants to clean up completed items across all lists.

    Returns:
        Confirmation that all done items were cleared.
    """
    db.delete_done()
    return "All completed items have been cleared."


def return_or_empty(value: list) -> str:
    if len(value) == 0:
        return "No information stored."
    return str(value)